# from decouple import AutoConfig

# config = AutoConfig()
import os
from dotenv import load_dotenv
load_dotenv()

# Database
DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_NAME = os.getenv("DATABASE_NAME")
SECRET_KEY = os.getenv("SECRET_KEY")
CAPTCHA_SECRET_KEY = os.getenv("CAPTCHA_SECRET_KEY")
ALLOWED_EXTENSIONS = os.getenv("ALLOWED_EXTENSIONS")
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
SENDGRID_FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL")


# JWT
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "30"))
# ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")

# MongoDB Collections
USER_COLLECTION = os.getenv("USER_COLLECTION")
CATEGORY_COLLECTION = os.getenv("CATEGORY_COLLECTION")
COMPANY_COLLECTION = os.getenv("COMPANY_COLLECTION")
CLIENT_COLLECTION = os.getenv("CLIENT_COLLECTION")
AGENT_COLLECTION = os.getenv("AGENT_COLLECTION")
CAR_BRAND_COLLECTION = os.getenv("CAR_BRAND_COLLECTION")
CAR_COLLECTION = os.getenv("CAR_COLLECTION")
VEHICLE_TYPE_COLLECTION = os.getenv("VEHICLE_TYPE_COLLECTION")
REVIEW_COLLECTION = os.getenv("REVIEW_COLLECTION")
VIDEOS_COLLECTION = os.getenv("VIDEOS_COLLECTION")
PHOTOS_COLLECTION=os.getenv("PHOTOS_COLLECTION")
PRIVACY_COLLECTION_NAME=os.getenv("PRIVACY_COLLECTION","privacy_policy")
ABOUT_US_COLLECTION=os.getenv("ABOUT_US_COLLECTION","about_us")
BOTTOM_SLIDER_COLLECTION=os.getenv("BOTTOM_SLIDER_COLLECTION","bottom_slider")
SETTINGS_COLLECTION=os.getenv("SETTINGS_COLLECTION","settings")
FAQ_COLLECTION=os.getenv("FAQ_COLLECTION","faq")
MESSAGES_COLLECTION=os.getenv("MESSAGES_COLLECTION","messages")
CHAT_COLLECTION=os.getenv("CHAT_COLLECTION","chats_Session")

S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
S3_BUCKET_URL = os.getenv("S3_BUCKET_URL")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION=os.getenv("AWS_REGION")
