from pydantic import BaseModel, Field

class CaptchaVerifyRequest(BaseModel):
    captcha_text: str = Field(..., description="The text of the CAPTCHA")
    token: str = Field(..., description="The token generated by the server")